name: Format and Lint

# on: [pull_request]
on: workflow_dispatch

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'

      - name: Clean Install Dependencies
        run: npm ci

      - name: Format with Prettier
        run: npm run format

      - name: Lint with ESLint
        run: npm run lint
